Algoritmo "duracao"
// 
//  
// Descrição   : Problema "duracao"
//Fazer um programa para ler uma duração de tempo em segundos, daí imprimir na tela esta duração no
//formato horas:minutos:segundos.
// Autor(a)    : Jefferson
// Data atual  : 04/10/2023
Var

        segundos:inteiro


Inicio


        escreva("Digite a duracao em segundos: "
        leia(segundos)
        
        

        escreva(


Fimalgoritmo